# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '__init__.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gl_map = QtWidgets.QGridLayout(self.groupBox)
        self.gl_map.setObjectName("gl_map")
        self.horizontalLayout.addWidget(self.groupBox)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 2)
        self.le_width = QtWidgets.QLineEdit(self.centralwidget)
        self.le_width.setText("")
        self.le_width.setObjectName("le_width")
        self.gridLayout.addWidget(self.le_width, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.le_height = QtWidgets.QLineEdit(self.centralwidget)
        self.le_height.setText("")
        self.le_height.setObjectName("le_height")
        self.gridLayout.addWidget(self.le_height, 2, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setEnabled(False)
        self.radioButton_3.setCheckable(True)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setCheckable(True)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setAutoRepeat(False)
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setEnabled(False)
        self.radioButton.setChecked(False)
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setCheckable(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setCheckable(True)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.gridLayout.addWidget(self.groupBox_2, 8, 0, 1, 2)
        self.cb_eight = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_eight.setObjectName("cb_eight")
        self.gridLayout.addWidget(self.cb_eight, 7, 0, 1, 2)
        self.le_obstacle_num = QtWidgets.QLineEdit(self.centralwidget)
        self.le_obstacle_num.setText("")
        self.le_obstacle_num.setObjectName("le_obstacle_num")
        self.gridLayout.addWidget(self.le_obstacle_num, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.pb_gen_map = QtWidgets.QPushButton(self.centralwidget)
        self.pb_gen_map.setObjectName("pb_gen_map")
        self.gridLayout.addWidget(self.pb_gen_map, 4, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hs_speed = QtWidgets.QSlider(self.groupBox_3)
        self.hs_speed.setMaximum(1000)
        self.hs_speed.setOrientation(QtCore.Qt.Horizontal)
        self.hs_speed.setObjectName("hs_speed")
        self.verticalLayout_2.addWidget(self.hs_speed)
        self.gridLayout.addWidget(self.groupBox_3, 5, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.radioButton_2.clicked.connect(self.radioButton_2.toggle)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QtAStar"))
        self.groupBox.setTitle(_translate("MainWindow", "地图"))
        self.label.setText(_translate("MainWindow", "宽度"))
        self.label_5.setText(_translate("MainWindow", "障碍数"))
        self.groupBox_2.setTitle(_translate("MainWindow", "符号说明"))
        self.radioButton_3.setText(_translate("MainWindow", "上一次的位置"))
        self.radioButton_2.setText(_translate("MainWindow", "当前位置"))
        self.radioButton.setText(_translate("MainWindow", "移动路径"))
        self.checkBox_2.setText(_translate("MainWindow", "可移动的位置"))
        self.checkBox_3.setText(_translate("MainWindow", "不可移动的位置（障碍）"))
        self.cb_eight.setText(_translate("MainWindow", "是否使用八方向寻路"))
        self.label_2.setText(_translate("MainWindow", "高度"))
        self.pb_gen_map.setText(_translate("MainWindow", "生成地图"))
        self.groupBox_3.setTitle(_translate("MainWindow", "移动速度调整"))
